// Author list exports for Wikiquote ingestion

import { TIER1_AUTHORS, TIER1_AUTHOR_NAMES } from './tier1-original';
import { TIER2_AUTHORS, TIER2_AUTHOR_NAMES } from './tier2-expanded';

export { TIER1_AUTHORS, TIER1_AUTHOR_NAMES } from './tier1-original';
export { TIER2_AUTHORS, TIER2_AUTHOR_NAMES } from './tier2-expanded';

// Combined list of all curated authors
export const ALL_CURATED_AUTHORS = [...TIER1_AUTHORS, ...TIER2_AUTHORS];
export const ALL_CURATED_AUTHOR_NAMES = [...TIER1_AUTHOR_NAMES, ...TIER2_AUTHOR_NAMES];

// Tier 3: Auto-discovered authors from category crawl
// This file is auto-generated by crawl-categories.ts
// Import will fail if tier3-crawled.ts doesn't exist yet - that's expected
let tier3Authors: Array<{ name: string; wikiquote_url: string; discovered_from_category: string; discovered_at: string }> = [];
let tier3AuthorNames: string[] = [];

try {
  const tier3Module = await import('./tier3-crawled');
  tier3Authors = tier3Module.TIER3_AUTHORS ?? [];
  tier3AuthorNames = tier3Module.TIER3_AUTHOR_NAMES ?? [];
} catch {
  // tier3-crawled.ts doesn't exist yet - that's fine
}

export const TIER3_AUTHORS = tier3Authors;
export const TIER3_AUTHOR_NAMES = tier3AuthorNames;

// Helper to get author info by name
export function getAuthorInfo(name: string): { name: string; era: string; tier: 1 | 2 | 3 } | null {
  const tier1 = TIER1_AUTHORS.find(a => a.name === name);
  if (tier1) return { ...tier1, tier: 1 };

  const tier2 = TIER2_AUTHORS.find(a => a.name === name);
  if (tier2) return { ...tier2, tier: 2 };

  const tier3 = TIER3_AUTHORS.find(a => a.name === name);
  if (tier3) return { name: tier3.name, era: 'Unknown', tier: 3 };

  return null;
}
