// Tier 2: Expanded curated authors for Phase 2A
// ~135 new authors across multiple categories

export const TIER2_AUTHORS: Array<{ name: string; era: string }> = [
  // Philosophers
  { name: 'Bertrand Russell', era: 'Modern' },
  { name: 'Ludwig Wittgenstein', era: 'Modern' },
  { name: 'John Locke', era: 'Enlightenment' },
  { name: 'David Hume', era: 'Enlightenment' },
  { name: 'Thomas Hobbes', era: 'Enlightenment' },
  { name: 'Baruch Spinoza', era: 'Enlightenment' },
  { name: 'Jean-Jacques Rousseau', era: 'Enlightenment' },
  { name: 'John Stuart Mill', era: 'Victorian' },
  { name: 'William James', era: 'Victorian' },
  { name: 'Simone de Beauvoir', era: 'Modern' },
  { name: 'Hannah Arendt', era: 'Modern' },
  { name: 'Michel Foucault', era: 'Contemporary' },
  { name: 'Karl Marx', era: 'Victorian' },
  { name: 'Thomas Aquinas', era: 'Medieval' },
  { name: 'Augustine of Hippo', era: 'Ancient' },
  { name: 'Francis Bacon', era: 'Renaissance' },
  { name: 'George Santayana', era: 'Modern' },
  { name: 'Alfred North Whitehead', era: 'Modern' },
  { name: 'Henri Bergson', era: 'Modern' },
  { name: 'Edmund Burke', era: 'Enlightenment' },
  { name: 'Thomas Paine', era: 'Enlightenment' },
  { name: 'Ayn Rand', era: 'Modern' },
  { name: 'Simone Weil', era: 'Modern' },

  // American Writers
  { name: 'Edgar Allan Poe', era: 'Romantic' },
  { name: 'Nathaniel Hawthorne', era: 'Romantic' },
  { name: 'Herman Melville', era: 'Romantic' },
  { name: 'Jack London', era: 'Modern' },
  { name: 'John Steinbeck', era: 'Modern' },
  { name: 'William Faulkner', era: 'Modern' },
  { name: 'Tennessee Williams', era: 'Modern' },
  { name: 'Truman Capote', era: 'Modern' },
  { name: 'Kurt Vonnegut', era: 'Contemporary' },
  { name: 'Ray Bradbury', era: 'Contemporary' },
  { name: 'Flannery O\'Connor', era: 'Modern' },
  { name: 'Willa Cather', era: 'Modern' },
  { name: 'Edith Wharton', era: 'Modern' },
  { name: 'Upton Sinclair', era: 'Modern' },
  { name: 'Sinclair Lewis', era: 'Modern' },
  { name: 'James Baldwin', era: 'Contemporary' },
  { name: 'Toni Morrison', era: 'Contemporary' },
  { name: 'Maya Angelou', era: 'Contemporary' },
  { name: 'Langston Hughes', era: 'Modern' },
  { name: 'Zora Neale Hurston', era: 'Modern' },

  // British Writers
  { name: 'Thomas Hardy', era: 'Victorian' },
  { name: 'Joseph Conrad', era: 'Victorian' },
  { name: 'D. H. Lawrence', era: 'Modern' },
  { name: 'E. M. Forster', era: 'Modern' },
  { name: 'Evelyn Waugh', era: 'Modern' },
  { name: 'Graham Greene', era: 'Modern' },
  { name: 'W. Somerset Maugham', era: 'Modern' },
  { name: 'Rudyard Kipling', era: 'Victorian' },
  { name: 'H. G. Wells', era: 'Modern' },
  { name: 'Arthur Conan Doyle', era: 'Victorian' },
  { name: 'C. S. Lewis', era: 'Modern' },
  { name: 'J. R. R. Tolkien', era: 'Modern' },
  { name: 'T. S. Eliot', era: 'Modern' },
  { name: 'W. H. Auden', era: 'Modern' },
  { name: 'Dylan Thomas', era: 'Modern' },
  { name: 'Robert Burns', era: 'Romantic' },
  { name: 'Alfred, Lord Tennyson', era: 'Victorian' },
  { name: 'John Milton', era: 'Renaissance' },
  { name: 'Geoffrey Chaucer', era: 'Medieval' },
  { name: 'William Hazlitt', era: 'Romantic' },

  // World Literature
  { name: 'Gabriel García Márquez', era: 'Contemporary' },
  { name: 'Jorge Luis Borges', era: 'Modern' },
  { name: 'Pablo Neruda', era: 'Modern' },
  { name: 'Rumi', era: 'Medieval' },
  { name: 'Khalil Gibran', era: 'Modern' },
  { name: 'Rabindranath Tagore', era: 'Modern' },
  { name: 'Umberto Eco', era: 'Contemporary' },
  { name: 'Italo Calvino', era: 'Contemporary' },
  { name: 'Milan Kundera', era: 'Contemporary' },
  { name: 'Honoré de Balzac', era: 'Romantic' },
  { name: 'Gustave Flaubert', era: 'Victorian' },
  { name: 'Marcel Proust', era: 'Modern' },
  { name: 'Stendhal', era: 'Romantic' },
  { name: 'Aleksandr Solzhenitsyn', era: 'Contemporary' },
  { name: 'Boris Pasternak', era: 'Modern' },
  { name: 'Nikos Kazantzakis', era: 'Modern' },
  { name: 'Hermann Hesse', era: 'Modern' },
  { name: 'Thomas Mann', era: 'Modern' },
  { name: 'Bertolt Brecht', era: 'Modern' },

  // Ancient/Classical
  { name: 'Sophocles', era: 'Ancient' },
  { name: 'Euripides', era: 'Ancient' },
  { name: 'Aeschylus', era: 'Ancient' },
  { name: 'Thucydides', era: 'Ancient' },
  { name: 'Xenophon', era: 'Ancient' },
  { name: 'Diogenes', era: 'Ancient' },
  { name: 'Ovid', era: 'Ancient' },
  { name: 'Horace', era: 'Ancient' },
  { name: 'Juvenal', era: 'Ancient' },
  { name: 'Lucretius', era: 'Ancient' },
  { name: 'Virgil', era: 'Ancient' },
  { name: 'Homer', era: 'Ancient' },
  { name: 'Sappho', era: 'Ancient' },
  { name: 'Pindar', era: 'Ancient' },
  { name: 'Aristophanes', era: 'Ancient' },

  // Historical Figures
  { name: 'Thomas Jefferson', era: 'Enlightenment' },
  { name: 'John Adams', era: 'Enlightenment' },
  { name: 'George Washington', era: 'Enlightenment' },
  { name: 'Frederick Douglass', era: 'Victorian' },
  { name: 'Susan B. Anthony', era: 'Victorian' },
  { name: 'Eleanor Roosevelt', era: 'Modern' },
  { name: 'John F. Kennedy', era: 'Contemporary' },
  { name: 'Franklin D. Roosevelt', era: 'Modern' },
  { name: 'Woodrow Wilson', era: 'Modern' },
  { name: 'Napoleon Bonaparte', era: 'Romantic' },
  { name: 'Julius Caesar', era: 'Ancient' },
  { name: 'Cleopatra', era: 'Ancient' },
  { name: 'Elizabeth I of England', era: 'Renaissance' },
  { name: 'Catherine the Great', era: 'Enlightenment' },
  { name: 'Pericles', era: 'Ancient' },
  { name: 'Alexander the Great', era: 'Ancient' },
  { name: 'Charlemagne', era: 'Medieval' },
  { name: 'Joan of Arc', era: 'Medieval' },

  // Modern Thinkers & Psychologists
  { name: 'Noam Chomsky', era: 'Contemporary' },
  { name: 'Marshall McLuhan', era: 'Contemporary' },
  { name: 'Susan Sontag', era: 'Contemporary' },
  { name: 'Christopher Hitchens', era: 'Contemporary' },
  { name: 'Carl Jung', era: 'Modern' },
  { name: 'Sigmund Freud', era: 'Modern' },
  { name: 'Joseph Campbell', era: 'Contemporary' },
  { name: 'Alan Watts', era: 'Contemporary' },
  { name: 'Buckminster Fuller', era: 'Contemporary' },
  { name: 'Erich Fromm', era: 'Modern' },
  { name: 'Viktor Frankl', era: 'Modern' },
  { name: 'Abraham Maslow', era: 'Contemporary' },
  { name: 'B. F. Skinner', era: 'Contemporary' },
  { name: 'Steven Pinker', era: 'Contemporary' },
  { name: 'Jordan Peterson', era: 'Contemporary' }
];

export const TIER2_AUTHOR_NAMES = TIER2_AUTHORS.map(a => a.name);
