// CCEL (Christian Classics Ethereal Library) Texts Configuration
// Defines all Christian theological texts to ingest

export interface CCELTextSource {
  id: string;
  title: string;
  author: string;
  authorBio?: string;
  era: 'Ancient' | 'Medieval' | 'Reformation' | 'Modern';
  tradition: string; // "Catholic", "Protestant", "Eastern Orthodox", etc.
  originalLanguage: string;
  genre: 'Theology' | 'Devotional' | 'Apologetics' | 'Mystical' | 'Allegory' | 'Philosophy';
  form: 'treatise' | 'meditation' | 'allegory' | 'confession' | 'summa' | 'sermon' | 'commentary';
  source: 'gutenberg' | 'ccel';
  gutenbergId?: number;
  urls: string[];
  tier: 1 | 2 | 3 | 4 | 5;
}

export const CCEL_TEXTS: CCELTextSource[] = [
  // ============================================
  // TIER 1: Must Have
  // ============================================

  {
    id: 'augustine-confessions',
    title: 'Confessions',
    author: 'Augustine of Hippo',
    authorBio: 'Bishop of Hippo, Doctor of the Church, influential early Christian theologian and philosopher. His writings shaped Western Christianity and philosophy.',
    era: 'Ancient',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'confession',
    source: 'gutenberg',
    gutenbergId: 3296,
    urls: ['https://www.gutenberg.org/cache/epub/3296/pg3296.txt'],
    tier: 1
  },
  {
    id: 'augustine-city-of-god',
    title: 'City of God',
    author: 'Augustine of Hippo',
    era: 'Ancient',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 45304,
    urls: ['https://www.gutenberg.org/cache/epub/45304/pg45304.txt'],
    tier: 1
  },
  {
    id: 'aquinas-summa-pt1',
    title: 'Summa Theologica (First Part)',
    author: 'Thomas Aquinas',
    authorBio: 'Dominican friar, philosopher, and Doctor of the Church. His Summa Theologica remains the defining work of scholastic theology.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'summa',
    source: 'gutenberg',
    gutenbergId: 17611,
    urls: ['https://www.gutenberg.org/cache/epub/17611/pg17611.txt'],
    tier: 1
  },
  {
    id: 'aquinas-summa-pt2a',
    title: 'Summa Theologica (First Part of the Second Part)',
    author: 'Thomas Aquinas',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'summa',
    source: 'gutenberg',
    gutenbergId: 17897,
    urls: ['https://www.gutenberg.org/cache/epub/17897/pg17897.txt'],
    tier: 1
  },
  {
    id: 'aquinas-summa-pt2b',
    title: 'Summa Theologica (Second Part of the Second Part)',
    author: 'Thomas Aquinas',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'summa',
    source: 'gutenberg',
    gutenbergId: 18755,
    urls: ['https://www.gutenberg.org/cache/epub/18755/pg18755.txt'],
    tier: 1
  },
  {
    id: 'aquinas-summa-pt3',
    title: 'Summa Theologica (Third Part)',
    author: 'Thomas Aquinas',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'summa',
    source: 'gutenberg',
    gutenbergId: 19950,
    urls: ['https://www.gutenberg.org/cache/epub/19950/pg19950.txt'],
    tier: 1
  },
  {
    id: 'calvin-institutes',
    title: 'Institutes of the Christian Religion',
    author: 'John Calvin',
    authorBio: 'French theologian and pastor during the Protestant Reformation. Principal figure in Reformed Christianity.',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 45001,
    urls: ['https://www.gutenberg.org/cache/epub/45001/pg45001.txt'],
    tier: 1
  },
  {
    id: 'bunyan-pilgrims-progress',
    title: "The Pilgrim's Progress",
    author: 'John Bunyan',
    authorBio: 'English writer and Puritan preacher. His allegorical work became one of the most significant works of religious English literature.',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Allegory',
    form: 'allegory',
    source: 'gutenberg',
    gutenbergId: 131,
    urls: ['https://www.gutenberg.org/cache/epub/131/pg131.txt'],
    tier: 1
  },
  {
    id: 'kempis-imitation',
    title: 'The Imitation of Christ',
    author: 'Thomas a Kempis',
    authorBio: 'German-Dutch canon regular of the Late Middle Ages. His devotional work is one of the most widely read Christian books.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 1653,
    urls: ['https://www.gutenberg.org/cache/epub/1653/pg1653.txt'],
    tier: 1
  },
  {
    id: 'lawrence-presence',
    title: 'The Practice of the Presence of God',
    author: 'Brother Lawrence',
    authorBio: 'Carmelite lay brother known for his profound spiritual wisdom despite humble station as a kitchen worker.',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'fr',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 5657,
    urls: ['https://www.gutenberg.org/cache/epub/5657/pg5657.txt'],
    tier: 1
  },
  {
    id: 'chesterton-orthodoxy',
    title: 'Orthodoxy',
    author: 'G.K. Chesterton',
    authorBio: 'English writer, philosopher, and Christian apologist known for his wit and paradoxical style.',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Apologetics',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 130,
    urls: ['https://www.gutenberg.org/cache/epub/130/pg130.txt'],
    tier: 1
  },
  {
    id: 'chesterton-everlasting-man',
    title: 'The Everlasting Man',
    author: 'G.K. Chesterton',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Apologetics',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 38357,
    urls: ['https://www.gutenberg.org/cache/epub/38357/pg38357.txt'],
    tier: 1
  },
  {
    id: 'chesterton-heretics',
    title: 'Heretics',
    author: 'G.K. Chesterton',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Apologetics',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 470,
    urls: ['https://www.gutenberg.org/cache/epub/470/pg470.txt'],
    tier: 1
  },
  {
    id: 'pascal-pensees',
    title: 'Pensees',
    author: 'Blaise Pascal',
    authorBio: 'French mathematician, physicist, and religious philosopher. His notes defending Christianity became one of the most influential apologetic works.',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'fr',
    genre: 'Apologetics',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 18269,
    urls: ['https://www.gutenberg.org/cache/epub/18269/pg18269.txt'],
    tier: 1
  },

  // ============================================
  // TIER 2: Important
  // ============================================

  {
    id: 'athanasius-incarnation',
    title: 'On the Incarnation',
    author: 'Athanasius of Alexandria',
    authorBio: 'Bishop of Alexandria, Doctor of the Church, chief defender of Trinitarianism against Arianism.',
    era: 'Ancient',
    tradition: 'Catholic',
    originalLanguage: 'grc',
    genre: 'Theology',
    form: 'treatise',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/athanasius/incarnation.txt'],
    tier: 2
  },
  {
    id: 'law-serious-call',
    title: 'A Serious Call to a Devout and Holy Life',
    author: 'William Law',
    authorBio: 'Church of England cleric whose devotional work influenced John Wesley and the Methodist movement.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 6966,
    urls: ['https://www.gutenberg.org/cache/epub/6966/pg6966.txt'],
    tier: 2
  },
  {
    id: 'edwards-religious-affections',
    title: 'A Treatise Concerning Religious Affections',
    author: 'Jonathan Edwards',
    authorBio: 'American revivalist preacher, philosopher, and Congregationalist Protestant theologian.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 11250,
    urls: ['https://www.gutenberg.org/cache/epub/11250/pg11250.txt'],
    tier: 2
  },
  {
    id: 'murray-abide',
    title: 'Abide in Christ',
    author: 'Andrew Murray',
    authorBio: 'South African writer, pastor, and Christian missionary. Prolific author of devotional works.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 17862,
    urls: ['https://www.gutenberg.org/cache/epub/17862/pg17862.txt'],
    tier: 2
  },
  {
    id: 'murray-humility',
    title: 'Humility',
    author: 'Andrew Murray',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 27150,
    urls: ['https://www.gutenberg.org/cache/epub/27150/pg27150.txt'],
    tier: 2
  },
  {
    id: 'bounds-prayer',
    title: 'Power Through Prayer',
    author: 'E.M. Bounds',
    authorBio: 'American Methodist clergyman whose writings on prayer have been widely influential.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 6514,
    urls: ['https://www.gutenberg.org/cache/epub/6514/pg6514.txt'],
    tier: 2
  },
  {
    id: 'teresa-interior-castle',
    title: 'The Interior Castle',
    author: 'Teresa of Avila',
    authorBio: 'Spanish Carmelite nun, mystic, and Doctor of the Church. Her mystical writings remain influential in Christian spirituality.',
    era: 'Reformation',
    tradition: 'Catholic',
    originalLanguage: 'es',
    genre: 'Mystical',
    form: 'meditation',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/teresa/castle2.txt'],
    tier: 2
  },
  {
    id: 'john-dark-night',
    title: 'Dark Night of the Soul',
    author: 'John of the Cross',
    authorBio: 'Spanish mystic, Carmelite friar, priest, and Doctor of the Church. Major figure in Counter-Reformation Catholic mysticism.',
    era: 'Reformation',
    tradition: 'Catholic',
    originalLanguage: 'es',
    genre: 'Mystical',
    form: 'meditation',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/john_cross/dark_night.txt'],
    tier: 2
  },
  {
    id: 'cloud-unknowing',
    title: 'The Cloud of Unknowing',
    author: 'Anonymous',
    authorBio: 'Anonymous 14th century English mystic. Work is considered a classic of Christian mysticism.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'enm',
    genre: 'Mystical',
    form: 'meditation',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/anonymous2/cloud.txt'],
    tier: 2
  },

  // ============================================
  // TIER 3: If Time Permits
  // ============================================

  {
    id: 'julian-revelations',
    title: 'Revelations of Divine Love',
    author: 'Julian of Norwich',
    authorBio: 'English anchoress and mystic, earliest known female author in the English language.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'enm',
    genre: 'Mystical',
    form: 'meditation',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/julian/revelations.txt'],
    tier: 3
  },
  {
    id: 'benedict-rule',
    title: 'The Rule of St. Benedict',
    author: 'Benedict of Nursia',
    authorBio: 'Father of Western monasticism, his Rule became the foundation for Western monastic life.',
    era: 'Ancient',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Devotional',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 50040,
    urls: ['https://www.gutenberg.org/cache/epub/50040/pg50040.txt'],
    tier: 3
  },
  {
    id: 'theologia-germanica',
    title: 'Theologia Germanica',
    author: 'Anonymous',
    authorBio: 'Anonymous 14th century German mystic. Martin Luther praised this work highly.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'de',
    genre: 'Mystical',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 31150,
    urls: ['https://www.gutenberg.org/cache/epub/31150/pg31150.txt'],
    tier: 3
  },
  {
    id: 'teresa-way-perfection',
    title: 'The Way of Perfection',
    author: 'Teresa of Avila',
    era: 'Reformation',
    tradition: 'Catholic',
    originalLanguage: 'es',
    genre: 'Mystical',
    form: 'meditation',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/teresa/way.txt'],
    tier: 3
  },
  {
    id: 'ryle-holiness',
    title: 'Holiness',
    author: 'J.C. Ryle',
    authorBio: 'First Anglican Bishop of Liverpool, evangelical churchman and prolific writer.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 26691,
    urls: ['https://www.gutenberg.org/cache/epub/26691/pg26691.txt'],
    tier: 3
  },
  {
    id: 'edwards-sinners',
    title: 'Sinners in the Hands of an Angry God',
    author: 'Jonathan Edwards',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 34632,
    urls: ['https://www.gutenberg.org/cache/epub/34632/pg34632.txt'],
    tier: 3
  },
  {
    id: 'spurgeon-checkbook',
    title: 'Faith\'s Checkbook',
    author: 'Charles Spurgeon',
    authorBio: 'English Baptist preacher known as the "Prince of Preachers". Immensely popular Victorian preacher.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 13224,
    urls: ['https://www.gutenberg.org/cache/epub/13224/pg13224.txt'],
    tier: 3
  },
  {
    id: 'spurgeon-morning-evening',
    title: 'Morning and Evening',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/spurgeon/morneve.txt'],
    tier: 3
  },
  {
    id: 'francis-little-flowers',
    title: 'The Little Flowers of St. Francis',
    author: 'Francis of Assisi',
    authorBio: 'Italian Catholic friar, founder of the Franciscans. Known for his love of nature and poverty.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'it',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 8702,
    urls: ['https://www.gutenberg.org/cache/epub/8702/pg8702.txt'],
    tier: 3
  },
  {
    id: 'fenelon-letters',
    title: 'Spiritual Letters',
    author: 'Francois Fenelon',
    authorBio: 'French Roman Catholic archbishop and theologian, known for his spiritual writings.',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'fr',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 15200,
    urls: ['https://www.gutenberg.org/cache/epub/15200/pg15200.txt'],
    tier: 3
  },
  {
    id: 'luther-bondage-will',
    title: 'The Bondage of the Will',
    author: 'Martin Luther',
    authorBio: 'German professor of theology and seminal figure in the Protestant Reformation.',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'treatise',
    source: 'ccel',
    urls: ['https://www.ccel.org/ccel/luther/bondage.txt'],
    tier: 3
  },
  {
    id: 'wesley-plain-account',
    title: 'A Plain Account of Christian Perfection',
    author: 'John Wesley',
    authorBio: 'English clergyman and theologian, founder of Methodism.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 27082,
    urls: ['https://www.gutenberg.org/cache/epub/27082/pg27082.txt'],
    tier: 3
  },
  {
    id: 'fox-journal',
    title: 'The Journal of George Fox',
    author: 'George Fox',
    authorBio: 'English Dissenter and founder of the Religious Society of Friends (Quakers).',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'confession',
    source: 'gutenberg',
    gutenbergId: 17854,
    urls: ['https://www.gutenberg.org/cache/epub/17854/pg17854.txt'],
    tier: 3
  },
  {
    id: 'bonaventure-journey',
    title: 'The Journey of the Mind to God',
    author: 'Bonaventure',
    authorBio: 'Italian medieval Franciscan scholastic theologian and Cardinal Bishop of Albano.',
    era: 'Medieval',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Mystical',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 14278,
    urls: ['https://www.gutenberg.org/cache/epub/14278/pg14278.txt'],
    tier: 3
  },

  // ============================================
  // TIER 4: Additional texts to reach target
  // ============================================

  {
    id: 'spurgeon-treasury',
    title: 'The Treasury of David Vol 1',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 14326,
    urls: ['https://www.gutenberg.org/cache/epub/14326/pg14326.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-treasury-2',
    title: 'The Treasury of David Vol 2',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 17927,
    urls: ['https://www.gutenberg.org/cache/epub/17927/pg17927.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-treasury-3',
    title: 'The Treasury of David Vol 3',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 19170,
    urls: ['https://www.gutenberg.org/cache/epub/19170/pg19170.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-sermons-1',
    title: 'Spurgeon\'s Sermons Vol 1',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 15215,
    urls: ['https://www.gutenberg.org/cache/epub/15215/pg15215.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-sermons-2',
    title: 'Spurgeon\'s Sermons Vol 2',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 15837,
    urls: ['https://www.gutenberg.org/cache/epub/15837/pg15837.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-sermons-3',
    title: 'Spurgeon\'s Sermons Vol 3',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 16382,
    urls: ['https://www.gutenberg.org/cache/epub/16382/pg16382.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-sermons-4',
    title: 'Spurgeon\'s Sermons Vol 4',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 16879,
    urls: ['https://www.gutenberg.org/cache/epub/16879/pg16879.txt'],
    tier: 4
  },
  {
    id: 'spurgeon-sermons-5',
    title: 'Spurgeon\'s Sermons Vol 5',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 17403,
    urls: ['https://www.gutenberg.org/cache/epub/17403/pg17403.txt'],
    tier: 4
  },
  {
    id: 'chrysostom-homilies-matthew',
    title: 'Homilies on the Gospel of Matthew',
    author: 'John Chrysostom',
    authorBio: 'Early Church Father, Archbishop of Constantinople, Doctor of the Church, known as the "Golden Mouth" for his eloquence.',
    era: 'Ancient',
    tradition: 'Catholic',
    originalLanguage: 'grc',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 28085,
    urls: ['https://www.gutenberg.org/cache/epub/28085/pg28085.txt'],
    tier: 4
  },
  {
    id: 'edwards-works-1',
    title: 'The Works of Jonathan Edwards Vol 1',
    author: 'Jonathan Edwards',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 35041,
    urls: ['https://www.gutenberg.org/cache/epub/35041/pg35041.txt'],
    tier: 4
  },
  {
    id: 'edwards-works-2',
    title: 'The Works of Jonathan Edwards Vol 2',
    author: 'Jonathan Edwards',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 35042,
    urls: ['https://www.gutenberg.org/cache/epub/35042/pg35042.txt'],
    tier: 4
  },
  {
    id: 'owen-sin',
    title: 'On the Mortification of Sin in Believers',
    author: 'John Owen',
    authorBio: 'English Nonconformist church leader, theologian, and academic administrator at the University of Oxford.',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 20556,
    urls: ['https://www.gutenberg.org/cache/epub/20556/pg20556.txt'],
    tier: 4
  },
  {
    id: 'murray-with-christ',
    title: 'With Christ in the School of Prayer',
    author: 'Andrew Murray',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 15252,
    urls: ['https://www.gutenberg.org/cache/epub/15252/pg15252.txt'],
    tier: 4
  },
  {
    id: 'murray-absolute-surrender',
    title: 'Absolute Surrender',
    author: 'Andrew Murray',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 6055,
    urls: ['https://www.gutenberg.org/cache/epub/6055/pg6055.txt'],
    tier: 4
  },
  {
    id: 'torrey-person-work',
    title: 'The Person and Work of the Holy Spirit',
    author: 'R.A. Torrey',
    authorBio: 'American evangelist, pastor, and writer associated with D.L. Moody.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 14702,
    urls: ['https://www.gutenberg.org/cache/epub/14702/pg14702.txt'],
    tier: 4
  },
  {
    id: 'gordon-quiet-talks',
    title: 'Quiet Talks on Prayer',
    author: 'S.D. Gordon',
    authorBio: 'American author and speaker, known for his "Quiet Talks" devotional series.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 15211,
    urls: ['https://www.gutenberg.org/cache/epub/15211/pg15211.txt'],
    tier: 4
  },
  {
    id: 'gordon-quiet-talks-jesus',
    title: 'Quiet Talks on Jesus',
    author: 'S.D. Gordon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 20044,
    urls: ['https://www.gutenberg.org/cache/epub/20044/pg20044.txt'],
    tier: 4
  },
  {
    id: 'augustine-sermons',
    title: 'Selected Sermons of St. Augustine',
    author: 'Augustine of Hippo',
    era: 'Ancient',
    tradition: 'Catholic',
    originalLanguage: 'la',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 41498,
    urls: ['https://www.gutenberg.org/cache/epub/41498/pg41498.txt'],
    tier: 4
  },
  {
    id: 'finney-lectures',
    title: 'Lectures on Revivals of Religion',
    author: 'Charles Finney',
    authorBio: 'American Presbyterian minister and leader in the Second Great Awakening.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 15272,
    urls: ['https://www.gutenberg.org/cache/epub/15272/pg15272.txt'],
    tier: 4
  },
  {
    id: 'finney-systematic-theology',
    title: 'Lectures on Systematic Theology',
    author: 'Charles Finney',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 18627,
    urls: ['https://www.gutenberg.org/cache/epub/18627/pg18627.txt'],
    tier: 4
  },
  {
    id: 'chesterton-whats-wrong',
    title: 'What\'s Wrong With the World',
    author: 'G.K. Chesterton',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Apologetics',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 1717,
    urls: ['https://www.gutenberg.org/cache/epub/1717/pg1717.txt'],
    tier: 4
  },
  {
    id: 'chesterton-ballad',
    title: 'The Ballad of the White Horse',
    author: 'G.K. Chesterton',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'allegory',
    source: 'gutenberg',
    gutenbergId: 1719,
    urls: ['https://www.gutenberg.org/cache/epub/1719/pg1719.txt'],
    tier: 4
  },
  {
    id: 'chesterton-st-francis',
    title: 'St. Francis of Assisi',
    author: 'G.K. Chesterton',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 31557,
    urls: ['https://www.gutenberg.org/cache/epub/31557/pg31557.txt'],
    tier: 4
  },
  {
    id: 'chesterton-st-thomas-aquinas',
    title: 'St. Thomas Aquinas',
    author: 'G.K. Chesterton',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'en',
    genre: 'Apologetics',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 22241,
    urls: ['https://www.gutenberg.org/cache/epub/22241/pg22241.txt'],
    tier: 4
  },
  {
    id: 'bounds-purpose-prayer',
    title: 'Purpose in Prayer',
    author: 'E.M. Bounds',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 5664,
    urls: ['https://www.gutenberg.org/cache/epub/5664/pg5664.txt'],
    tier: 4
  },
  {
    id: 'bounds-preacher-prayer',
    title: 'Preacher and Prayer',
    author: 'E.M. Bounds',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 6543,
    urls: ['https://www.gutenberg.org/cache/epub/6543/pg6543.txt'],
    tier: 4
  },
  {
    id: 'baxter-saints-rest',
    title: 'The Saints\' Everlasting Rest',
    author: 'Richard Baxter',
    authorBio: 'English Puritan church leader, theologian and poet.',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 15201,
    urls: ['https://www.gutenberg.org/cache/epub/15201/pg15201.txt'],
    tier: 4
  },
  {
    id: 'baxter-reformed-pastor',
    title: 'The Reformed Pastor',
    author: 'Richard Baxter',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 17530,
    urls: ['https://www.gutenberg.org/cache/epub/17530/pg17530.txt'],
    tier: 4
  },
  {
    id: 'moody-secret-power',
    title: 'Secret Power',
    author: 'D.L. Moody',
    authorBio: 'American evangelist and publisher who founded Moody Church and Moody Bible Institute.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 13224,
    urls: ['https://www.gutenberg.org/cache/epub/36680/pg36680.txt'],
    tier: 4
  },
  {
    id: 'moody-way-to-god',
    title: 'The Way to God',
    author: 'D.L. Moody',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 17620,
    urls: ['https://www.gutenberg.org/cache/epub/17620/pg17620.txt'],
    tier: 4
  },
  {
    id: 'henry-commentary-1',
    title: 'Matthew Henry\'s Commentary on Genesis',
    author: 'Matthew Henry',
    authorBio: 'Nonconformist minister and author, best known for his comprehensive Bible commentary.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47221,
    urls: ['https://www.gutenberg.org/cache/epub/47221/pg47221.txt'],
    tier: 4
  },
  {
    id: 'henry-commentary-2',
    title: 'Matthew Henry\'s Commentary on Exodus',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47222,
    urls: ['https://www.gutenberg.org/cache/epub/47222/pg47222.txt'],
    tier: 4
  },
  {
    id: 'henry-commentary-psalms',
    title: 'Matthew Henry\'s Commentary on Psalms',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47223,
    urls: ['https://www.gutenberg.org/cache/epub/47223/pg47223.txt'],
    tier: 4
  },
  {
    id: 'henry-commentary-matthew',
    title: 'Matthew Henry\'s Commentary on Matthew',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47226,
    urls: ['https://www.gutenberg.org/cache/epub/47226/pg47226.txt'],
    tier: 4
  },
  {
    id: 'henry-commentary-romans',
    title: 'Matthew Henry\'s Commentary on Romans',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47229,
    urls: ['https://www.gutenberg.org/cache/epub/47229/pg47229.txt'],
    tier: 4
  },

  // ============================================
  // TIER 5: More texts to reach 100k passages
  // ============================================

  {
    id: 'spurgeon-sermons-6',
    title: 'Spurgeon\'s Sermons Vol 6',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 18032,
    urls: ['https://www.gutenberg.org/cache/epub/18032/pg18032.txt'],
    tier: 5
  },
  {
    id: 'spurgeon-sermons-7',
    title: 'Spurgeon\'s Sermons Vol 7',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 18695,
    urls: ['https://www.gutenberg.org/cache/epub/18695/pg18695.txt'],
    tier: 5
  },
  {
    id: 'spurgeon-sermons-8',
    title: 'Spurgeon\'s Sermons Vol 8',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 19286,
    urls: ['https://www.gutenberg.org/cache/epub/19286/pg19286.txt'],
    tier: 5
  },
  {
    id: 'spurgeon-sermons-9',
    title: 'Spurgeon\'s Sermons Vol 9',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 19757,
    urls: ['https://www.gutenberg.org/cache/epub/19757/pg19757.txt'],
    tier: 5
  },
  {
    id: 'spurgeon-sermons-10',
    title: 'Spurgeon\'s Sermons Vol 10',
    author: 'Charles Spurgeon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 20340,
    urls: ['https://www.gutenberg.org/cache/epub/20340/pg20340.txt'],
    tier: 5
  },
  {
    id: 'henry-commentary-acts',
    title: 'Matthew Henry\'s Commentary on Acts',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47227,
    urls: ['https://www.gutenberg.org/cache/epub/47227/pg47227.txt'],
    tier: 5
  },
  {
    id: 'henry-commentary-john',
    title: 'Matthew Henry\'s Commentary on John',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47228,
    urls: ['https://www.gutenberg.org/cache/epub/47228/pg47228.txt'],
    tier: 5
  },
  {
    id: 'henry-commentary-corinthians',
    title: 'Matthew Henry\'s Commentary on Corinthians',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47230,
    urls: ['https://www.gutenberg.org/cache/epub/47230/pg47230.txt'],
    tier: 5
  },
  {
    id: 'henry-commentary-hebrews',
    title: 'Matthew Henry\'s Commentary on Hebrews',
    author: 'Matthew Henry',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 47233,
    urls: ['https://www.gutenberg.org/cache/epub/47233/pg47233.txt'],
    tier: 5
  },
  {
    id: 'wesley-sermons',
    title: 'Wesley\'s Sermons',
    author: 'John Wesley',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 17535,
    urls: ['https://www.gutenberg.org/cache/epub/17535/pg17535.txt'],
    tier: 5
  },
  {
    id: 'fletcher-checks',
    title: 'Checks to Antinomianism',
    author: 'John Fletcher',
    authorBio: 'English clergyman and theologian, close associate of John Wesley.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 21251,
    urls: ['https://www.gutenberg.org/cache/epub/21251/pg21251.txt'],
    tier: 5
  },
  {
    id: 'whitefield-sermons',
    title: 'George Whitefield\'s Sermons',
    author: 'George Whitefield',
    authorBio: 'Anglican cleric and evangelist, leader of the First Great Awakening.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'sermon',
    source: 'gutenberg',
    gutenbergId: 25803,
    urls: ['https://www.gutenberg.org/cache/epub/25803/pg25803.txt'],
    tier: 5
  },
  {
    id: 'edwards-freedom-will',
    title: 'Freedom of the Will',
    author: 'Jonathan Edwards',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 11250,
    urls: ['https://www.gutenberg.org/cache/epub/3196/pg3196.txt'],
    tier: 5
  },
  {
    id: 'owen-hebrews-1',
    title: 'Exposition of Hebrews Vol 1',
    author: 'John Owen',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 57091,
    urls: ['https://www.gutenberg.org/cache/epub/57091/pg57091.txt'],
    tier: 5
  },
  {
    id: 'murray-spirit-christ',
    title: 'The Spirit of Christ',
    author: 'Andrew Murray',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 27153,
    urls: ['https://www.gutenberg.org/cache/epub/27153/pg27153.txt'],
    tier: 5
  },
  {
    id: 'murray-new-life',
    title: 'The New Life',
    author: 'Andrew Murray',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 27148,
    urls: ['https://www.gutenberg.org/cache/epub/27148/pg27148.txt'],
    tier: 5
  },
  {
    id: 'murray-full-blessing',
    title: 'The Full Blessing of Pentecost',
    author: 'Andrew Murray',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 27151,
    urls: ['https://www.gutenberg.org/cache/epub/27151/pg27151.txt'],
    tier: 5
  },
  {
    id: 'simpson-fourfold-gospel',
    title: 'The Fourfold Gospel',
    author: 'A.B. Simpson',
    authorBio: 'Canadian preacher, theologian, and author who founded the Christian and Missionary Alliance.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 22447,
    urls: ['https://www.gutenberg.org/cache/epub/22447/pg22447.txt'],
    tier: 5
  },
  {
    id: 'gordon-quiet-talks-power',
    title: 'Quiet Talks on Power',
    author: 'S.D. Gordon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 24619,
    urls: ['https://www.gutenberg.org/cache/epub/24619/pg24619.txt'],
    tier: 5
  },
  {
    id: 'gordon-quiet-talks-service',
    title: 'Quiet Talks on Service',
    author: 'S.D. Gordon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 26038,
    urls: ['https://www.gutenberg.org/cache/epub/26038/pg26038.txt'],
    tier: 5
  },
  {
    id: 'gordon-quiet-talks-home',
    title: 'Quiet Talks on Home Ideals',
    author: 'S.D. Gordon',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 26039,
    urls: ['https://www.gutenberg.org/cache/epub/26039/pg26039.txt'],
    tier: 5
  },
  {
    id: 'guyon-experiencing-depths',
    title: 'Experiencing the Depths of Jesus Christ',
    author: 'Madame Guyon',
    authorBio: 'French mystic and quietist, known for her writings on contemplative prayer.',
    era: 'Modern',
    tradition: 'Catholic',
    originalLanguage: 'fr',
    genre: 'Mystical',
    form: 'meditation',
    source: 'gutenberg',
    gutenbergId: 14020,
    urls: ['https://www.gutenberg.org/cache/epub/14020/pg14020.txt'],
    tier: 5
  },
  {
    id: 'brooks-precious-remedies',
    title: 'Precious Remedies Against Satan\'s Devices',
    author: 'Thomas Brooks',
    authorBio: 'English Nonconformist Puritan preacher and prolific author.',
    era: 'Reformation',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 19389,
    urls: ['https://www.gutenberg.org/cache/epub/19389/pg19389.txt'],
    tier: 5
  },
  {
    id: 'pink-attributes-god',
    title: 'The Attributes of God',
    author: 'A.W. Pink',
    authorBio: 'English Christian evangelist and Biblical scholar known for his sound Reformed theological works.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 25178,
    urls: ['https://www.gutenberg.org/cache/epub/25178/pg25178.txt'],
    tier: 5
  },
  {
    id: 'pink-sovereignty-god',
    title: 'The Sovereignty of God',
    author: 'A.W. Pink',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'treatise',
    source: 'gutenberg',
    gutenbergId: 27153,
    urls: ['https://www.gutenberg.org/cache/epub/27153/pg27153.txt'],
    tier: 5
  },
  {
    id: 'mueller-autobiography',
    title: 'Autobiography of George Mueller',
    author: 'George Mueller',
    authorBio: 'Christian evangelist known for his orphanages and faith-based approach to funding.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Devotional',
    form: 'confession',
    source: 'gutenberg',
    gutenbergId: 41054,
    urls: ['https://www.gutenberg.org/cache/epub/41054/pg41054.txt'],
    tier: 5
  },
  {
    id: 'maclaren-expositions-1',
    title: 'Expositions of Holy Scripture: Genesis',
    author: 'Alexander Maclaren',
    authorBio: 'British Baptist minister known for his Bible expositions.',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 25831,
    urls: ['https://www.gutenberg.org/cache/epub/25831/pg25831.txt'],
    tier: 5
  },
  {
    id: 'maclaren-expositions-2',
    title: 'Expositions of Holy Scripture: Exodus',
    author: 'Alexander Maclaren',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 26070,
    urls: ['https://www.gutenberg.org/cache/epub/26070/pg26070.txt'],
    tier: 5
  },
  {
    id: 'maclaren-expositions-psalms',
    title: 'Expositions of Holy Scripture: Psalms',
    author: 'Alexander Maclaren',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 26321,
    urls: ['https://www.gutenberg.org/cache/epub/26321/pg26321.txt'],
    tier: 5
  },
  {
    id: 'maclaren-expositions-matthew',
    title: 'Expositions of Holy Scripture: Matthew',
    author: 'Alexander Maclaren',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 26705,
    urls: ['https://www.gutenberg.org/cache/epub/26705/pg26705.txt'],
    tier: 5
  },
  {
    id: 'maclaren-expositions-mark',
    title: 'Expositions of Holy Scripture: Mark',
    author: 'Alexander Maclaren',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 26928,
    urls: ['https://www.gutenberg.org/cache/epub/26928/pg26928.txt'],
    tier: 5
  },
  {
    id: 'maclaren-expositions-john',
    title: 'Expositions of Holy Scripture: John',
    author: 'Alexander Maclaren',
    era: 'Modern',
    tradition: 'Protestant',
    originalLanguage: 'en',
    genre: 'Theology',
    form: 'commentary',
    source: 'gutenberg',
    gutenbergId: 27137,
    urls: ['https://www.gutenberg.org/cache/epub/27137/pg27137.txt'],
    tier: 5
  }
];

export function getTextById(id: string): CCELTextSource | undefined {
  return CCEL_TEXTS.find(t => t.id === id);
}

export function getTextsByTier(tier: 1 | 2 | 3): CCELTextSource[] {
  return CCEL_TEXTS.filter(t => t.tier === tier);
}

export function getAllTexts(): CCELTextSource[] {
  return CCEL_TEXTS;
}
