// Perseus priority texts configuration
// Maps priority texts to their file paths and metadata

export interface TextConfig {
  id: string;
  title: string;
  author: string;
  authorId: string; // TLG or PHI identifier for author
  workId: string;   // TLG or PHI identifier for work
  language: "grc" | "la"; // Original language (Greek or Latin)
  nationality: "Greek" | "Roman";
  genre: string;
  form: "poetry" | "dialogue" | "drama" | "prose";
  tier: 1 | 2;
  translationPath: string; // Relative to repos directory
  era: string;
  birthYear?: number;
  deathYear?: number;
}

// Tier 1: Must-have Greatest Hits
export const TIER1_TEXTS: TextConfig[] = [
  // Homer
  {
    id: "homer-iliad",
    title: "Iliad",
    author: "Homer",
    authorId: "tlg0012",
    workId: "tlg001",
    language: "grc",
    nationality: "Greek",
    genre: "Epic",
    form: "poetry",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0012/tlg001/tlg0012.tlg001.perseus-eng3.xml",
    era: "Ancient",
    birthYear: -800,
    deathYear: -701,
  },
  {
    id: "homer-odyssey",
    title: "Odyssey",
    author: "Homer",
    authorId: "tlg0012",
    workId: "tlg002",
    language: "grc",
    nationality: "Greek",
    genre: "Epic",
    form: "poetry",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0012/tlg002/tlg0012.tlg002.perseus-eng3.xml",
    era: "Ancient",
    birthYear: -800,
    deathYear: -701,
  },
  // Plato
  {
    id: "plato-republic",
    title: "Republic",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg030",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0059/tlg030/tlg0059.tlg030.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  {
    id: "plato-symposium",
    title: "Symposium",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg011",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0059/tlg011/tlg0059.tlg011.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  {
    id: "plato-apology",
    title: "Apology",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg002",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0059/tlg002/tlg0059.tlg002.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  // Aristotle
  {
    id: "aristotle-nicomachean-ethics",
    title: "Nicomachean Ethics",
    author: "Aristotle",
    authorId: "tlg0086",
    workId: "tlg010",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "prose",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0086/tlg010/tlg0086.tlg010.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -384,
    deathYear: -322,
  },
  {
    id: "aristotle-poetics",
    title: "Poetics",
    author: "Aristotle",
    authorId: "tlg0086",
    workId: "tlg034",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "prose",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0086/tlg034/tlg0086.tlg034.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -384,
    deathYear: -322,
  },
  // Sophocles
  {
    id: "sophocles-oedipus-rex",
    title: "Oedipus Rex",
    author: "Sophocles",
    authorId: "tlg0011",
    workId: "tlg004",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0011/tlg004/tlg0011.tlg004.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -496,
    deathYear: -406,
  },
  {
    id: "sophocles-antigone",
    title: "Antigone",
    author: "Sophocles",
    authorId: "tlg0011",
    workId: "tlg002",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0011/tlg002/tlg0011.tlg002.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -496,
    deathYear: -406,
  },
  // Euripides
  {
    id: "euripides-medea",
    title: "Medea",
    author: "Euripides",
    authorId: "tlg0006",
    workId: "tlg003",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0006/tlg003/tlg0006.tlg003.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -480,
    deathYear: -406,
  },
  // Aeschylus - Oresteia (trilogy: Agamemnon, Libation Bearers, Eumenides)
  {
    id: "aeschylus-agamemnon",
    title: "Agamemnon",
    author: "Aeschylus",
    authorId: "tlg0085",
    workId: "tlg001",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0085/tlg001/tlg0085.tlg001.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -525,
    deathYear: -456,
  },
  {
    id: "aeschylus-libation-bearers",
    title: "Libation Bearers",
    author: "Aeschylus",
    authorId: "tlg0085",
    workId: "tlg002",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0085/tlg002/tlg0085.tlg002.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -525,
    deathYear: -456,
  },
  {
    id: "aeschylus-eumenides",
    title: "Eumenides",
    author: "Aeschylus",
    authorId: "tlg0085",
    workId: "tlg003",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0085/tlg003/tlg0085.tlg003.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -525,
    deathYear: -456,
  },
  // Virgil
  {
    id: "virgil-aeneid",
    title: "Aeneid",
    author: "Virgil",
    authorId: "phi0690",
    workId: "phi003",
    language: "la",
    nationality: "Roman",
    genre: "Epic",
    form: "poetry",
    tier: 1,
    translationPath: "canonical-latinLit/data/phi0690/phi003/phi0690.phi003.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -70,
    deathYear: -19,
  },
  // Ovid
  {
    id: "ovid-metamorphoses",
    title: "Metamorphoses",
    author: "Ovid",
    authorId: "phi0959",
    workId: "phi006",
    language: "la",
    nationality: "Roman",
    genre: "Epic",
    form: "poetry",
    tier: 1,
    translationPath: "canonical-latinLit/data/phi0959/phi006/phi0959.phi006.perseus-eng3.xml",
    era: "Ancient",
    birthYear: -43,
    deathYear: 17,
  },
  // Herodotus
  {
    id: "herodotus-histories",
    title: "Histories",
    author: "Herodotus",
    authorId: "tlg0016",
    workId: "tlg001",
    language: "grc",
    nationality: "Greek",
    genre: "History",
    form: "prose",
    tier: 1,
    translationPath: "canonical-greekLit/data/tlg0016/tlg001/tlg0016.tlg001.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -484,
    deathYear: -425,
  },
];

// Tier 2: Important additions
export const TIER2_TEXTS: TextConfig[] = [
  // More Plato
  {
    id: "plato-phaedrus",
    title: "Phaedrus",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg012",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0059/tlg012/tlg0059.tlg012.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  {
    id: "plato-phaedo",
    title: "Phaedo",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg004",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0059/tlg004/tlg0059.tlg004.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  {
    id: "plato-meno",
    title: "Meno",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg006",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0059/tlg006/tlg0059.tlg006.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  {
    id: "plato-crito",
    title: "Crito",
    author: "Plato",
    authorId: "tlg0059",
    workId: "tlg003",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "dialogue",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0059/tlg003/tlg0059.tlg003.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -428,
    deathYear: -348,
  },
  // Aristotle
  {
    id: "aristotle-politics",
    title: "Politics",
    author: "Aristotle",
    authorId: "tlg0086",
    workId: "tlg035",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0086/tlg035/tlg0086.tlg035.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -384,
    deathYear: -322,
  },
  {
    id: "aristotle-rhetoric",
    title: "Rhetoric",
    author: "Aristotle",
    authorId: "tlg0086",
    workId: "tlg038",
    language: "grc",
    nationality: "Greek",
    genre: "Philosophy",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0086/tlg038/tlg0086.tlg038.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -384,
    deathYear: -322,
  },
  // More Sophocles
  {
    id: "sophocles-ajax",
    title: "Ajax",
    author: "Sophocles",
    authorId: "tlg0011",
    workId: "tlg003",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0011/tlg003/tlg0011.tlg003.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -496,
    deathYear: -406,
  },
  {
    id: "sophocles-electra",
    title: "Electra",
    author: "Sophocles",
    authorId: "tlg0011",
    workId: "tlg005",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0011/tlg005/tlg0011.tlg005.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -496,
    deathYear: -406,
  },
  // More Euripides
  {
    id: "euripides-bacchae",
    title: "Bacchae",
    author: "Euripides",
    authorId: "tlg0006",
    workId: "tlg002",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0006/tlg002/tlg0006.tlg002.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -480,
    deathYear: -406,
  },
  {
    id: "euripides-hippolytus",
    title: "Hippolytus",
    author: "Euripides",
    authorId: "tlg0006",
    workId: "tlg005",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0006/tlg005/tlg0006.tlg005.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -480,
    deathYear: -406,
  },
  // More Aeschylus
  {
    id: "aeschylus-prometheus-bound",
    title: "Prometheus Bound",
    author: "Aeschylus",
    authorId: "tlg0085",
    workId: "tlg006",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0085/tlg006/tlg0085.tlg006.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -525,
    deathYear: -456,
  },
  {
    id: "aeschylus-persians",
    title: "Persians",
    author: "Aeschylus",
    authorId: "tlg0085",
    workId: "tlg004",
    language: "grc",
    nationality: "Greek",
    genre: "Tragedy",
    form: "drama",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0085/tlg004/tlg0085.tlg004.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -525,
    deathYear: -456,
  },
  // Thucydides
  {
    id: "thucydides-peloponnesian-war",
    title: "History of the Peloponnesian War",
    author: "Thucydides",
    authorId: "tlg0003",
    workId: "tlg001",
    language: "grc",
    nationality: "Greek",
    genre: "History",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0003/tlg001/tlg0003.tlg001.perseus-eng4.xml",
    era: "Ancient",
    birthYear: -460,
    deathYear: -400,
  },
  // More Virgil
  {
    id: "virgil-eclogues",
    title: "Eclogues",
    author: "Virgil",
    authorId: "phi0690",
    workId: "phi001",
    language: "la",
    nationality: "Roman",
    genre: "Pastoral",
    form: "poetry",
    tier: 2,
    translationPath: "canonical-latinLit/data/phi0690/phi001/phi0690.phi001.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -70,
    deathYear: -19,
  },
  {
    id: "virgil-georgics",
    title: "Georgics",
    author: "Virgil",
    authorId: "phi0690",
    workId: "phi002",
    language: "la",
    nationality: "Roman",
    genre: "Didactic",
    form: "poetry",
    tier: 2,
    translationPath: "canonical-latinLit/data/phi0690/phi002/phi0690.phi002.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -70,
    deathYear: -19,
  },
  // Seneca
  {
    id: "seneca-epistles",
    title: "Moral Epistles",
    author: "Seneca",
    authorId: "phi1017",
    workId: "phi011",
    language: "la",
    nationality: "Roman",
    genre: "Philosophy",
    form: "prose",
    tier: 2,
    translationPath: "canonical-latinLit/data/phi1017/phi011/phi1017.phi011.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -4,
    deathYear: 65,
  },
  // Horace
  {
    id: "horace-odes",
    title: "Odes",
    author: "Horace",
    authorId: "phi0893",
    workId: "phi001",
    language: "la",
    nationality: "Roman",
    genre: "Lyric",
    form: "poetry",
    tier: 2,
    translationPath: "canonical-latinLit/data/phi0893/phi001/phi0893.phi001.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -65,
    deathYear: -8,
  },
  {
    id: "horace-satires",
    title: "Satires",
    author: "Horace",
    authorId: "phi0893",
    workId: "phi004",
    language: "la",
    nationality: "Roman",
    genre: "Satire",
    form: "poetry",
    tier: 2,
    translationPath: "canonical-latinLit/data/phi0893/phi004/phi0893.phi004.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -65,
    deathYear: -8,
  },
  {
    id: "horace-ars-poetica",
    title: "Ars Poetica",
    author: "Horace",
    authorId: "phi0893",
    workId: "phi006",
    language: "la",
    nationality: "Roman",
    genre: "Didactic",
    form: "poetry",
    tier: 2,
    translationPath: "canonical-latinLit/data/phi0893/phi006/phi0893.phi006.perseus-eng2.xml",
    era: "Ancient",
    birthYear: -65,
    deathYear: -8,
  },
  // Plutarch - Parallel Lives
  {
    id: "plutarch-alexander",
    title: "Life of Alexander",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg047",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg047/tlg0007.tlg047.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-caesar",
    title: "Life of Caesar",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg048",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg048/tlg0007.tlg048.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-theseus",
    title: "Life of Theseus",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg001",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg001/tlg0007.tlg001.perseus-eng3.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-pericles",
    title: "Life of Pericles",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg012",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg012/tlg0007.tlg012.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-alcibiades",
    title: "Life of Alcibiades",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg017",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg017/tlg0007.tlg017.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-demosthenes",
    title: "Life of Demosthenes",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg054",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg054/tlg0007.tlg054.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-cicero",
    title: "Life of Cicero",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg055",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg055/tlg0007.tlg055.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-antony",
    title: "Life of Antony",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg058",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg058/tlg0007.tlg058.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
  {
    id: "plutarch-brutus",
    title: "Life of Brutus",
    author: "Plutarch",
    authorId: "tlg0007",
    workId: "tlg061",
    language: "grc",
    nationality: "Greek",
    genre: "Biography",
    form: "prose",
    tier: 2,
    translationPath: "canonical-greekLit/data/tlg0007/tlg061/tlg0007.tlg061.perseus-eng2.xml",
    era: "Ancient",
    birthYear: 46,
    deathYear: 120,
  },
];

// All texts combined
export const ALL_TEXTS: TextConfig[] = [...TIER1_TEXTS, ...TIER2_TEXTS];

// Get unique authors from text configs
export function getUniqueAuthors(): Map<string, TextConfig> {
  const authorMap = new Map<string, TextConfig>();
  for (const text of ALL_TEXTS) {
    if (!authorMap.has(text.authorId)) {
      authorMap.set(text.authorId, text);
    }
  }
  return authorMap;
}
